/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.alignmentsystems.matching;
/******************************************************************************
 * 
 *	Author			: John Greenan
 *	Date            : 24th August 2023
 *	Copyright       : Alignment Systems Ltd 2023
 * 
 *	Artefact		: App
 * 
 *****************************************************************************/

public class App {
	
	public static void main(String[] args) {		
		MatchingEngineWrapper wrapper = new MatchingEngineWrapper(args);
		wrapper.fireItUp();
	} 
}